---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# contexttab

<!-- badges: start -->
<!-- badges: end -->

The goal of contexttab is to provide R bindings to SAP's Tabular in-context learner (ICL), sap-rpt-1-oss (fka ConTextTab).

## Installation

You can install the development version of contexttab like so:

``` r
pak::pak("frankiethull/contexttab")

# then do:
contexttab::create_contexttab_env()
contexttab::use_contexttab_env()
contexttab::install_contexttab_dependencies()
```

## Example

setting up a training & testing dataset for sap-rtp-oss models. 

```{r example}
library(contexttab)
library(rsample)
contexttab::use_contexttab_env()

corn_data <- maize::corn_data

corn_splits <- initial_validation_split(corn_data)
train <- training(corn_splits)
validate <- validation(corn_splits)
test <- testing(corn_splits)
```

### contexttab classification

```{r}
fit <- sap_rpt_oss_classifier_fit(
 X = train |> dplyr::select(-type),  y = train$type
)

# Make predictions
predictions <- predict(fit, test |> dplyr::select(-type))
probs <- predict(fit, test |> dplyr::select(-type), type = "proba")

predictions |> head()
```

```{r}
probs |> head()
```

### contexttab regression
```{r}
fit <- sap_rpt_oss_regressor_fit(
 X = train |> dplyr::select(-height),  y = train$height
)

# Make predictions
predictions <- predict(fit, test |> dplyr::select(-height))

predictions |> head()
```
